// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package database

import (
	"context"
)

type Querier interface {
	CreateLikeRelation(ctx context.Context, arg CreateLikeRelationParams) (LikeRelations, error)
	CreateRelations(ctx context.Context, arg CreateRelationsParams) (Relations, error)
	CreateTweet(ctx context.Context, arg CreateTweetParams) (Tweets, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (Users, error)
	DecrementFollower(ctx context.Context, username string) (Users, error)
	DecrementFollowing(ctx context.Context, username string) (Users, error)
	DecrementLike(ctx context.Context, id int64) (Tweets, error)
	DeleteLikeRelation(ctx context.Context, arg DeleteLikeRelationParams) error
	DeleteRelation(ctx context.Context, arg DeleteRelationParams) error
	DeleteTweet(ctx context.Context, id int64) error
	GetFollower(ctx context.Context, arg GetFollowerParams) ([]Relations, error)
	GetFollowing(ctx context.Context, arg GetFollowingParams) ([]Relations, error)
	GetLikeRelation(ctx context.Context, arg GetLikeRelationParams) (LikeRelations, error)
	GetListTweets(ctx context.Context, arg GetListTweetsParams) ([]Tweets, error)
	GetRelations(ctx context.Context, arg GetRelationsParams) (Relations, error)
	GetTweet(ctx context.Context, id int64) (Tweets, error)
	GetUser(ctx context.Context, username string) (Users, error)
	IncrementFollower(ctx context.Context, username string) (Users, error)
	IncrementFollowing(ctx context.Context, username string) (Users, error)
	IncrementLike(ctx context.Context, id int64) (Tweets, error)
	UpdateEmail(ctx context.Context, arg UpdateEmailParams) (Users, error)
	UpdateName(ctx context.Context, arg UpdateNameParams) (Users, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (Users, error)
}

var _ Querier = (*Queries)(nil)
